id = "material-icon-theme-with-odin"
name = "Material Icon Theme (with odin)"
version = "0.1.2"
schema_version = 1
authors = ["Zed Industries <support@zed.dev>"]
description = "Material Design icons with odin."
repository = "https://github.com/LucasCzerny/material-icon-theme/"
